apiVersion: v2
name: itl-kube-prometheus-stack
description: kube-prometheus-stack
version: 1.0.0
appVersion: "66.2.2"

dependencies:
  - name: kube-prometheus-stack
    version: "77.9.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    alias: kube-prometheus-stack
